name:
  ImageMagick

repository:
  https://github.com/ImageMagick/ImageMagick

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/animate
  - bin/compare
  - bin/composite
  - bin/conjure
  - bin/convert
  - bin/display
  - bin/identify
  - bin/import
  - bin/magick
  - bin/magick-script
  - bin/Magick++-config
  - bin/MagickCore-config
  - bin/MagickWand-config
  - bin/mogrify
  - bin/montage
  - bin/stream

dependencies:
  libpng.org: ^1
  ijg.org: ^9
  freetype.org: ^2
  github.com/carlobaldassi/liblqr: ^0.4.3
  simplesystems.org/libtiff: ^4
  littlecms.com: ^2
  openexr.com: ^3
  openjpeg.org: ^2
  google.com/webp: ^1
  gnu.org/libtool: ^2  # the modules system needs libltdl
  tukaani.org/xz: ^5
  jpeg.org/jpegxl: ^0.11
  github.com/strukturag/libheif: ^1
  libzip.org: ^1.11

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
    sourceware.org/bzip2: ^1
    zlib.net: ^1
    x.org/libX11: ^1
    gnome.org/libxml2: ^2
    llvm.org/openmp: ^20
    # ^^ TODO we want this on darwin too but we need to make our own llvm work
    # because the Apple provided one does not support `-fopenmp`

env:
  MAGICK_HOME: '{{prefix}}'
  CPATH: "{{prefix}}/include/Magick-{{version.major}}:$CPATH"
