repository:
  https://github.com/webmproject/libwebp

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/cwebp
  - bin/dwebp
  - bin/gif2webp
  - bin/img2webp
  - bin/webpinfo
  - bin/webpmux

darwin:
  programs:
    - bin/vwebp

dependencies:
  sf.net/giflib: ^5
  libjpeg-turbo.org: ^3
  libpng.org: ^1
  simplesystems.org/libtiff: ^4
