name:
  GNU Automake

homepage:
  https://www.gnu.org/software/automake/

programs:
  - bin/automake
  - bin/aclocal

dependencies:
  gnu.org/autoconf: ^2.65.0

platforms:
  - darwin/aarch64
  - linux/x86-64
