platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/ldapcompare
  - bin/ldapdelete
  - bin/ldapexop
  - bin/ldapmodify
  - bin/ldapmodrdn
  - bin/ldappasswd
  - bin/ldapsearch
  - bin/ldapurl
  - bin/ldapvc
  - bin/ldapwhoami

dependencies:
  openssl.org: ^3
  # linux:
  #   github.com/util-linux/util-linux: '*'
