runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v2
      if: runner.os == 'Windows'

    - run: |
        "$PWD\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

        git fetch origin pkgx
        git checkout FETCH_HEAD -- pkgx.exe
        Move-Item -Path pkgx.exe -Destination bin

        Get-ChildItem -Path brewkit -Recurse -Filter *.ts | ForEach-Object { deno cache $_.FullName }

        choco install make -y
      shell: pwsh
      if: runner.os == 'Windows'

    - run: |
        echo "$PWD/bin" >> $GITHUB_PATH

        case $(uname) in
        Linux)
          # $HOME is different in the docker image vs. github actions
          ln -s /root/.pkgx $HOME
          ln -s /root/.cache $HOME
          ./bin/pkg-convert
          ;;
        Darwin)
          curl https://pkgx.sh/$(uname)/$(uname -m).tgz | sudo tar xz -C /usr/local/bin
          find brewkit -name \*.ts | xargs pkgx deno^2 cache
          ./bin/pkg-convert
          ;;
        *)
          make -f ./bin/pkg-convert
          ;;
        esac


      shell: bash
