runs:
  using: composite
  steps:
    - run: |
        case $(cat /etc/debian_version 2>/dev/null) in
        buster/sid|10.*)
          # $HOME is different from the docker image and in github actions
          ln -s /root/.pkgx $HOME
          ln -s /root/.cache $HOME
          ;;
        *)
          curl https://pkgx.sh/$(uname)/$(uname -m).tgz | sudo tar xz -C /usr/local/bin
          ;;
        esac
      shell: bash

    - uses: actions/checkout@v4
      with:
        ref: pkgx
        path: tmp

    - run: |
        mv tmp/pkgx3-$(uname) /usr/local/bin/pkgx3
        rm -rf tmp
        if [ $(uname) = Darwin ]; then
          find lib bin .github -name \*.ts | xargs pkgx deno^2 cache
        fi
      shell: bash
