runs:
  using: composite
  steps:
    # unavoidable for some projects on windows
    # TODO we can probs save 20–30s and make a TS function to add this env
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'

    - uses: pkgxdev/setup@v4
      if: runner.os != 'Linux'

    - run: |
        Join-Path $PWD "bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        Get-ChildItem -Path brewkit -Recurse -Filter *.ts | ForEach-Object { .\\bin\\pkgx deno^2 -q cache $_.FullName }
        .\\bin\\pkgx deno^2 -q cache .\\.github\\scripts\\generate-versions
      shell: pwsh
      if: runner.os == 'Windows'

    - run: |
        case $(uname) in
        Linux)
          # $HOME is different in the docker image vs. github actions
          ln -s /root/.pkgx $HOME
          ln -s /root/.cache $HOME
          echo "$PWD/bin" >> $GITHUB_PATH
          ;;
        Darwin)
          find brewkit -name \*.ts | xargs pkgx deno^2 --quiet cache
          pkgx deno^2 --quiet cache .github/scripts/generate-versions
          echo "$PWD/bin" >> $GITHUB_PATH
          ;;
        esac

        # we have to run this inside git-bash on Windows
        ./bin/pkg-convert
      shell: bash
