platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/cairo-trace

dependencies:
  freedesktop.org/fontconfig: ^2
  freedesktop.org/pixman: ^0.44
  sourceware.org/bzip2: ^1
  gnome.org/glib: ^2
  freetype.org: ^2
  libpng.org: ^1
  # oberhumer.com/lzo: '*'

linux:
  dependencies:
  x.org/libX11: ^1.8
  # x.org/xcb: '*'
  x.org/libXext: ^1.3
  # x.org/xrender: '*'
