platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/lua
  - bin/luac

linux:
  dependencies:
    gnu.org/readline: ^8

#TODO
#companions:
#  - luarocks.org

#TODO test that this fails then try again
# env:
#   LUA_PATH: $LUA_PATH;{{prefix}}/share/lua/{{version.marketing}}/?.lua;{{prefix}}/share/lua/{{version.marketing}}/?/init.lua;{{prefix}}/lib/lua/{{version.marketing}}/?.lua;{{prefix}}/lib/lua/{{version.marketing}}/?/init.lua
#   LUA_CPATH: $LUA_CPATH;{{prefix}}/lib/lua/{{version.marketing}}/?.so;{{prefix}}/lib/lua/{{version.marketing}}/loadall.so
