name:
  GNU MPC

homepage:
  https://www.multiprecision.org

description:
  Arbitrarily high precision complex number arithmetic with correct rounding

dependencies:
  gnu.org/mpfr: ^4

darwin:
  dependencies:
    gnu.org/gmp: ^6 # on Linux we statically link due to libstdc++ sucking

platforms:
  - darwin/aarch64
  - linux/x86-64
