name:
  GNU Bison

homepage:
  https://www.gnu.org/software/bison/

repository:
  https://github.com/akimd/bison

programs:
  - bin/bison
  - bin/yacc

linux:
  dependencies:
    gnu.org/m4: ^1.4.6

platforms:
  - darwin/aarch64
  - linux/x86-64
