name:
  Rust

repository:
  https://github.com/rust-lang/rust

programs:
  - bin/rustc
  - bin/cargo
  - bin/cargo-clippy
  - bin/cargo-fmt
  - bin/clippy-driver
  - bin/rls
  - bin/rust-analyzer
  - bin/rust-gdb
  - bin/rust-gdbgui
  - bin/rust-lldb
  - bin/rustdoc
  - bin/rustfmt

linux:
  dependencies:
    zlib.net: ^1
  companions:
    - llvm.org

platforms:
  - darwin
  - linux
