repository:
  https://github.com/AcademySoftwareFoundation/openexr

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/exr2aces
  - bin/exrenvmap
  - bin/exrheader
  - bin/exrmakepreview
  - bin/exrmaketiled
  - bin/exrmultipart
  - bin/exrmultiview
  - bin/exrstdattr

dependencies:
  openexr.com/Imath: ^3

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
    zlib.net: ^1
