repository:
  https://github.com/p11-glue/p11-kit

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/p11-kit
  - bin/trust

dependencies:
  gnu.org/libtasn1: ^4

linux:
  dependencies:
    sourceware.org/libffi: ^3

env:
  CPATH: '{{prefix}}/include/p11-kit-1:$CPATH'
