repository:
  https://github.com/strukturag/libheif

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/heif-enc
  - bin/heif-info
  - bin/heif-thumbnailer

dependencies:
  aomedia.org/aom: ^3
  libjpeg-turbo.org: ^3
  github.com/strukturag/libde265: ^1
  libpng.org: ^1
  # freedesktop.org/shared-mime-info: '*'
  videolan.org/x265: ^4

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
