name:
  libdeflate

repository:
  https://github.com/ebiggers/libdeflate

programs:
  - bin/gzip
  - bin/gunzip
  - bin/libdeflate-gzip
  - bin/libdeflate-gunzip

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64
