repository:
  https://github.com/libass/libass

platforms:
  - darwin/aarch64
  - linux/x86-64

dependencies:
  freetype.org: ^2
  gnu.org/fribidi: ^1
  harfbuzz.org: ^11
  github.com/adah1972/libunibreak: ^6

linux:
  dependencies:
    freedesktop.org/fontconfig: 2
