name:
  GCC

homepage:
  https://gcc.gnu.org/

programs:
  - bin/cc
  - bin/c++
  - bin/cpp
  - bin/ar
  - bin/ranlib
  - bin/nm

  - bin/gcc
  - bin/g++
  - bin/gcc-ar
  - bin/gcc-nm
  - bin/gcc-ranlib

  - bin/lto-dump

  - bin/gcov
  - bin/gcov-dump
  - bin/gcov-tool

# we can support more platforms but at this time don’t want the hassle
platforms:
  - linux/x86-64

dependencies:
  gnu.org/mpc: ^1.3

# linux:
#   dependencies:
#     gnu.org/gcc/libstdcxx: ^14

# we don’t provide a shared libgcc or libstdc++
# we probs should provide a shared libgcc in the future but a share dlibstdc++
# is a can of worms and we probs should never bother
env:
  CFLAGS: -static-libgcc $CFLAGS
  CXXFLAGS: -static-libgcc $CXXFLAGS
  LDFLAGS: -static-libgcc $LDFLAGS

companions:
  - gnu.org/binutils
