name:
  rustup

repository:
  https://github.com/rust-lang/rustup

programs:
  - bin/rustup-init

linux:
  dependencies:
    zlib.net: ^1
  companions:
    - llvm.org

windows:
  companions:
    - git-scm.org

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64
