repository:
  https://github.com/silnrsi/graphite

homepage:
  https://graphite.sil.org

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/gr2fonttest

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
