name:
  PCRE2

repository:
  https://github.com/PCRE2Project/pcre2

homepage:
  https://www.pcre.org

platforms:
  - darwin/aarch64
  - linux/x86-64

# FIXME these are all versionless for <=8.45
programs:
  - bin/pcre2-config
  - bin/pcre2grep
  - bin/pcre2test

linux:
  dependencies:
    zlib.net: ^1
    sourceware.org/bzip2: ^1
    gnu.org/gcc/libstdcxx: ^14
    # ^^ FIXME actually only required for pcre1
