repository:
  https://github.com/harfbuzz/harfbuzz

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/hb-shape
  - bin/hb-subset
  - bin/hb-view

dependencies:
  cairographics.org: ^1
  freetype.org: ^2
  gnome.org/glib: ^2
  sil.org/graphite: ^1.3
  unicode.org: ^77
