repository:
  https://github.com/strukturag/libde265

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/acceleration_speed
  - bin/bjoentegaard
  - bin/block-rate-estim
  - bin/gen-enc-table
  - bin/rd-curves
  - bin/tests
  - bin/yuv-distortion

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
