platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/ffmpeg
  - bin/ffprobe

dependencies:
  sf.net/lame: '>=3.98.3'
  # libsdl.org: ^2
  freetype.org: ^2
  harfbuzz.org: ^8
  videolan.org/x264: ^0.165
  videolan.org/x265: ^4
  google.com/libvpx: ^1
  # opus-codec.org: ^1
  google.com/webp: ^1
  gnu.org/fribidi: ^1
