repository:
  https://github.com/GNOME/libxml2

env:
  PYTHONPATH: "{{prefix}}/lib/python3.9/site-packages:$PYTHONPATH"
  CPATH: "{{prefix}}/include/libxml2:$CPATH"

linux:
  dependencies:
    zlib.net: ^1

programs:
  - bin/xml2-config
  - bin/xmlcatalog
  - bin/xmllint

platforms:
  - darwin/aarch64
  - linux/x86-64
