homepage:
  https://poppler.freedesktop.org/

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/pdfattach
  - bin/pdfdetach
  - bin/pdffonts
  - bin/pdfimages
  - bin/pdfinfo
  - bin/pdfseparate
  - bin/pdftocairo
  - bin/pdftohtml
  - bin/pdftoppm
  - bin/pdftops
  - bin/pdftotext
  - bin/pdfunite

dependencies:
  boost.org: ^1
  cairographics.org: ^1
  freedesktop.org/fontconfig: ^2
  freetype.org: ^2
  openjpeg.org: ^2
  simplesystems.org/libtiff: ^4
  littlecms.com: ^2.9
  mozilla.org/nss: ^3
  gnupg.org/gpgme: ^1.19

linux:
  dependencies:
    curl.se: ^8
    zlib.net: ^1
    gnu.org/gcc/libstdcxx: ^14
