name: GNU gettext

homepage:
  https://www.gnu.org/software/gettext/

dependencies:
  gnu.org/libiconv: ^1

companions:
  - tukaani.org/xz # autopoint needs this to unpack archives

programs:
  - bin/autopoint
  - bin/envsubst
  - bin/gettext
  - bin/gettext.sh
  - bin/gettextize
  - bin/msgattrib
  - bin/msgcat
  - bin/msgcmp
  - bin/msgcomm
  - bin/msgconv
  - bin/msgen
  - bin/msgexec
  - bin/msgfilter
  - bin/msgfmt
  - bin/msggrep
  - bin/msginit
  - bin/msgmerge
  - bin/msgunfmt
  - bin/msguniq
  - bin/ngettext
  - bin/recode-sr-latin
  - bin/xgettext

platforms:
  - darwin/aarch64
  - linux/x86-64
