platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/update-mime-database

dependencies:
  gnome.org/glib: ^2
  # gnu.org/gettext: ^0.21

linux:
  dependencies:
    gnome.org/libxml2: ^2
