repository:
  https://github.com/OpenPrinting/cups

homepage:
  https://openprinting.github.io/cups/

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/cups-config
  - bin/ippeveprinter
  - bin/ipptool

dependencies:
  kerberos.org: ^1

linux:
  dependencies:
    zlib.net: ^1
    openssl.org: ^3
