repository:
  https://github.com/AcademySoftwareFoundation/Imath

platforms:
  - darwin/aarch64
  - linux/x86-64

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14

env:
  CPATH: '{{prefix}}/include/Imath:$CPATH'
