name:
  Node.js

repository:
  https://github.com/nodejs/node

# companions:
#   - nodejs.org/npm

dependencies:
  openssl.org: ^1.1,^3
  zlib.net: ^1
  # linux:
  #   gnu.org/gcc/libstdcxx: '*' # libstdc++, since 22.2.0

programs:
  - bin/node

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64
