name:
  Node.js

repository:
  https://github.com/nodejs/node

dependencies:
  openssl.org: ^1.1,^3

# NOTE we static link the vendored libunicode because maintaining the
# variance and having pkgx have to vary libunicode so often is a PITA
# TODO don’t do this?

programs:
  - bin/node
