distributable:
  url: https://ftp.gnu.org/gnu/patch/patch-{{version}}.tar.gz
  strip-components: 1

versions:
  url: https://ftp.gnu.org/gnu/patch/
  match: /patch-(\d+\.\d+(\.\d+)?)\.tar\.gz/
  strip:
    - /patch-/
    - /.tar.gz/

name: GNU Patch

programs:
  - bin/patch

platforms:
  - darwin/aarch64
  - linux/x86-64
