platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/gdbus
  - bin/gdbus-codegen
  - bin/gio
  - bin/gio-querymodules
  - bin/glib-compile-resources
  - bin/glib-compile-schemas
  - bin/glib-genmarshal
  - bin/glib-gettextize
  - bin/glib-mkenums
  - bin/gobject-query
  - bin/gresource
  - bin/gsettings
  - bin/gtester
  - bin/gtester-report

dependencies:
  gnu.org/gettext: ^0.24
  sourceware.org/libffi: ^3
  pcre.org: ^10

env:
  CPATH: '{{prefix}}/include/glib-2.0:{{prefix}}/lib/glib-2.0/include:$CPATH'
