repository:
  https://github.com/libsdl-org/SDL

platforms:
  - darwin/aarch64
  - linux/x86-64

linux:
  dependencies:
    x.org/libX11: ^1.8
    x.org/xcursor: ^1.2
    # x.org/xi: '*'
    # x.org/xrandr: '*''
    x.org/xscrnsaver: ^1.2
    x.org/libXext: ^1.3

env:
  CPATH: '{{prefix}}/include{{version.major}}:$CPATH'
