name:
  libgcc & libstdc++

homepage:
  https://gcc.gnu.org/onlinedocs/libstdc++/

platforms:
  - linux/x86-64

env:
  # ensure clang etc. can find the c++ header files
  CPLUS_INCLUDE_PATH: '{{prefix}}/include/c++/{{version}}:{{prefix}}/include/c++/{{version}}/x86_64-pc-linux-gnu:$CPLUS_INCLUDE_PATH'
  # ensure clang etc. can find libgcc’s binary bits
  # CFLAGS: -B{{prefix}}/lib/gcc/x86_64-pc-linux-gnu/{{version}} $CFLAGS
