repository:
  https://github.com/llvm/llvm-project

programs:
  - bin/llvm-profdata

linux:
  companions:
    - llvm.org
  dependencies:
    zlib.net: ^1
    gnu.org/gcc/libstdcxx: ^14

platforms:
  - linux/x86-64
