name:
  CA Certficates

homepage:
  https://curl.se/docs/caextract.html

brief:
  Secure connection certificates

description:
  Certificates for authenticating and verifying secure TLS/SSL connections

env:
  SSL_CERT_FILE: "{{prefix}}/share/ca-certs.pem"

platforms: "*"
