repository:
  https://github.com/GNOME/libxslt

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/xslt-config
  - bin/xsltproc


dependencies:
  gnome.org/libxml2: ^2
  # ^^ requires a newer version than macOS provides
