repository:
  https://github.com/xiph/flac

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/flac

dependencies:
  xiph.org/ogg: ^1.3.5

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
