name:
  Go

repository:
  https://github.com/golang/go

programs:
  - bin/go
  - bin/gofmt

linux:
  dependencies:
    curl.se/ca-certs: '*'

platforms:
  - darwin/aarch64
  - darwin/x86-64
  - linux/aarch64
  - linux/x86-64
  - windows/x86-64
