name:
  ncurses

homepage:
  https://invisible-island.net/ncurses/

programs:
  - bin/captoinfo
  - bin/clear
  - bin/infocmp
  - bin/infotocap
  - bin/ncursesw6-config
  - bin/reset
  - bin/tabs
  - bin/tic
  - bin/toe
  - bin/tput
  - bin/tset

env:
  TERMINFO_DIRS: /usr/share/terminfo:{{prefix}}/share/terminfo:$TERMINFO_DIRS
  # ^^ we delegate to the system first since they may apply platform specific info

platforms:
  - darwin/aarch64
  - linux/x86-64
