name:
  Expat

repository:
  https://github.com/libexpat/libexpat

programs:
  - bin/xmlwf

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64

deprecated-names:
  - github.com/libexpat/libexpat
