distributable:
  url: https://github.com/cli/cli/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

repository:
  https://github.com/cli/cli

programs:
  - bin/gh

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64
