name: Ruby

repository:
  https://github.com/ruby/ruby

dependencies:
  openssl.org: ^3
  pyyaml.org/libyaml: ^0.2.5

dev:
  - .rubyversion

programs:
  - bin/ruby
  - bin/erb
  - bin/irb
  - bin/rake
  - bin/rdoc
  - bin/ri
  - bin/bundle
  - bin/bundler
  - bin/gem

platforms:
  - darwin
  - linux
