name:
  JPEG XL

repository:
  https://github.com/libjxl/libjxl

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/cjxl
  - bin/djxl
  - bin/jxlinfo

dependencies:
  libpng.org: ^1
  openexr.com: ^3
  sf.net/giflib: ^5
  littlecms.com: ^2.13
  google.com/webp: ^1
  google.com/brotli: ^1
  google.com/highway: ^1

linux:
  dependencies:
    gnu.org/gcc/libstdcxx: ^14
