name:
  rustup

aliases:
  - rust

repository:
  https://github.com/rust-lang/rustup

programs:
  - bin/rustup-init
  - bin/rustup
  #TODO we provide these but it results in a conflict with rust-lang.org
  #TODO allow sane-defaults for conflits to be set? To what end tho?
  # - bin/rustc
  # - bin/cargo
  # - bin/cargo-clippy
  # - bin/cargo-fmt
  # - bin/clippy-driver
  # - bin/rls
  # - bin/rust-analyzer
  # - bin/rust-gdb
  # - bin/rust-gdbgui
  # - bin/rust-lldb
  # - bin/rustdoc
  # - bin/rustfmt

linux:
  dependencies:
    zlib.net: ^1
  companions:
    - llvm.org

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64

env:
  CARGO_INSTALL_ROOT: "{{home}}/.local/bin"
