repository:
  https://github.com/erlang/otp

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/ct_run
  - bin/dialyzer
  - bin/epmd
  - bin/erl
  - bin/erlc
  - bin/escript
  - bin/run_erl
  - bin/to_erl
  - bin/typer

dependencies:
  openssl.org: ^3

linux:
  dependencies:
    invisible-island.net/ncurses: ^6
    gnu.org/gcc/libstdcxx: ^14

env:
  ERL_ROOTDIR: ${{prefix}}/lib/erlang
