name:
  Deno

repository:
  https://github.com/denoland/deno

programs:
  - bin/deno

# TODO compile deno ourselves and make this the default
# Fix deno update logic to update via ourselves
env:
  DENO_INSTALL_ROOT: "{{home}}/.local/bin"
