platforms:
  - darwin/aarch64
  - linux/x86-64

dependencies:
  libpng.org: ^1

linux:
  dependencies:
    zlib.net: ^1
    sourceware.org/bzip2: ^1

env:
  CPATH: '{{prefix}}/include/freetype2:$CPATH'
