name:
  GNU Autoconf

homepage:
  https://www.gnu.org/software/autoconf/

programs:
  - bin/autoconf
  - bin/autoheader
  - bin/autom4te
  - bin/autoreconf
  - bin/autoscan
  - bin/autoupdate
  - bin/ifnames

dependencies:
  gnu.org/m4: ^1.4

platforms:
  - darwin/aarch64
  - linux/x86-64
