name:
  Python

repository:
  https://github.com/python/cpython

companions:
  - python.org/pip

dependencies:
  openssl.org: ^3
  tukaani.org/xz: ^5
  github.com/libexpat: ^2
  # ^^ strictly not required on mac, but performance guided build fails
  # ^^ without it
  bytereef.org/mpdecimal: ^4

linux:
  dependencies:
    sourceware.org/bzip2: ^1
    gnu.org/readline: ^7,^8
    invisible-island.net/ncurses: ^6
    zlib.net: ^1
    sqlite.org: ^3
    sourceware.org/libffi: ^3

programs:
  - bin/python
  - bin/python-config
  - bin/pydoc

windows:
  programs:
    - bin/pythonw

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64
