name:
  Python

repository:
  https://github.com/python/cpython

dependencies:
  openssl.org: ^3
  tukaani.org/xz: ^5
  github.com/libexpat: ^2  # macOS provides this—but the performance-guided-build fails without it
  bytereef.org/mpdecimal: ^4  # macOS provided version is outdated

programs:
  - bin/python
  - bin/python-config
  - bin/pydoc
  - bin/pip

windows:
  programs:
    - bin/pythonw
