platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/g-ir-annotation-tool
  - bin/g-ir-compiler
  - bin/g-ir-generate
  - bin/g-ir-inspect
  - bin/g-ir-scanner

dependencies:
  gnome.org/glib: ^2

linux:
  dependencies:
    sourceware.org/libffi: ^3
