platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/g-ir-annotation-tool
  - bin/g-ir-compiler
  - bin/g-ir-generate
  - bin/g-ir-inspect
  - bin/g-ir-scanner

dependencies:
  gnome.org/glib: ^2
  sourceware.org/libffi: ^3
  # gnu.org/bison: ^3
  # github.com/westes/flex: ^2
