name:
  SQLite

repository:
  https://github.com/sqlite/sqlite

linux:
  dependencies:
    zlib.net: ^1
    gnu.org/readline: ^8

windows:
  dependencies:
    zlib.net: ^1

programs:
  - bin/sqlite3

platforms:
  - darwin/aarch64
  - linux/x86-64
  - windows/x86-64
