name:
  GIFLIB

homepage:
  https://giflib.sf.net

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/gif2rgb
  - bin/gifbuild
  - bin/gifclrmp
  - bin/giffix
  - bin/giftext
  - bin/giftool
