platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/pango-list
  - bin/pango-segmentation
  - bin/pango-view

dependencies:
  cairographics.org: ^1.18
  freetype.org: ^2
  gnome.org/glib: ^2
  harfbuzz.org: ^11
  freedesktop.org/fontconfig: ^2
  gnu.org/fribidi: ^1

linux:
  dependencies:
    sourceware.org/libffi: ^3
