#!/bin/sh
#
# intelligently inject our rpath into the arguments for build tools
# this is more reliable than setting LDFLAGS which often can cause other weird breakage
# without our rpath things don’t link correctly, which is annoying but seems
# to be because Open Source doesn’t typically use rpath stuff and we do for relocability
# reasons

tool=$(basename "$0")
export _PKGX_DIR="$(cd "$(dirname "$0")/.." && pwd)/pkgs"

case $tool in
cc|gcc|clang|c++|g++|clang++)
  exec ruby "$0" "$@"
  ;;
ld|lld|lld-link|ld64.lld)
  for word in "$@"; do
    if test "$word" = -r; then
      exec /usr/bin/"$tool" "$@"
    fi
  done

  exec /usr/bin/"$tool" "$@" -rpath "$_PKGX_DIR"
  ;;
*)
  exit 2
  ;;
esac


#!/usr/bin/ruby

$pkgx_dir = ENV['_PKGX_DIR']
exe = File.basename($0)

# remove duplicates since this in fact embeds the rpath multiple times
# and omit -nodefaultrpaths since it is not a valid flag for clang
args = ARGV.map do |arg|
  arg unless arg == "-Wl,-rpath,#$pkgx_dir" or arg == "-nodefaultrpaths"
end.compact

# find next example of ourselves
# this will either pick the Apple provided clang or the pkgx one
exe_path = ENV['PATH'].split(":").filter { |path|
  path != File.dirname(__FILE__)
}.map { |path|
  "#{path}/#{exe}"
}.find { |path|
  File.exist?(path)
}

abort "couldn’t find #{exe} in `PATH`" unless exe_path

args = args.filter do |arg|
  arg != '-Werror'
end

for arg in args do
  # figuring out what “mode” we are operating in is hard
  # we don’t want to add this linker command always because it causes a warning to be
  # output if we are not outputing executables/dylibs and this warning can break
  # configure scripts, however the below is not fully encompassing
  # we aren't sure what the rules are TBH, possibly it is as simple as if the output (`-o`)
  # is a .o then we don’t add the rpath
  if arg.start_with? '-l' or arg.end_with? '.dylib'
    exec exe_path, *args, "-Wl,-rpath,#$pkgx_dir"
  end
end

exec exe_path, *args
