name:
  Zstandard

repository:
  https://github.com/facebook/zstd

dependencies:
  lz4.org: ^1
  tukaani.org/xz: ^5

linux:
  dependencies:
    zlib.net: ^1

platforms:
  - darwin/aarch64
  - linux/x86-64

programs:
  - bin/pzstd
  - bin/unzstd
  - bin/zstd
  - bin/zstdcat
  - bin/zstdgrep
  - bin/zstdless
  - bin/zstdmt
